assignment/urls.py
from django.urls import path
# from .views import UserListView
from . import views
from cruds_adminlte.urls import crud_for_model
from .forms import SelectCourseForm
from .models import SelectCourse
from django.conf import settings
from .views import GradeUpdateView, StatusUpdateView, CourseUpdateView


app_name = 'assignment_app'
urlpatterns = [
    
    path('register_course/<str:pk>/', views.register_course, name='register-course'),
    path('main_dashboard/<str:pk>/', views.main_dashboard, name='main-dashboard'),
    path('assignment/<int:pk>/<str:i_n>/', views.submit_assignment, name='submit-assignment'),
    path('assignment/delete/<str:pk>/<str:i_n>/', views.del_assignment, name='delete-assignment'),
    path('assignment/update/<str:pk>/', views.update_assignment, name='update-assignment'),
    path('assignment/view_assignment_pdf/<str:pk>/', views.viewAssignmentPDF, name='view-assignment-pdf'),
    path('download_assignment/<str:pk>/', views.download_pdf, name='download-file'),
    path('score_student_section/<str:pk>/<str:a_pk>/', views.student_result, name='score-student-section'),
    path('assignment/all_students/<str:pk>/', views.all_students, name='all-students'),
    path('assignment/dashboard/', views.dashboard, name='dashboard'),
    path('assignment/submission_denied/<str:pk>/<str:i_n>/', views.submission_denied, name='submission-denied'),
    path('assignment/score_student_section/update/<int:pk>/<str:s>/<int:o_pk>/<int:ind>/', GradeUpdateView.as_view(), name='update-grade'),
    
    path('course/update/<str:pk>/', views.update_courses, name='update-courses'),
    
    path('update/<str:pk>/', views.update_submitted, name='update-status'),
    path('view_result/<str:pk>/<str:i_n>/', views.query_results, name='view-result'),
    path('all_courses/<str:pk>/', views.all_courses, name='all-courses'),
    path('del_courses/<str:pk>/', views.del_course, name='del-course'),
    path('del_upload_file/<str:pk>/', views.del_upload_file, name='del-upload-file'),
    path('student_dashboard/', views.student_dashboard, name='student-dashboard'),
    path('del_choose_course/<str:pk>/', views.del_choose_course, name='del-choose-course'),
    path('create_pdf/', views.create_pdf, name='create-pdf'),
    path('reults_denied/<str:pk>/', views.results_denied, name='results-denied'),
    path('student_results_list/<str:c>/<int:pk>/', views.student_results_list, name='student-list'),
    path('grade_student/<int:pk>/<int:index>/', views.grade_student, name='grade-student'),

    path('pdf_view/<str:c>/', views.ViewPDF.as_view(), name="pdf-view"),
    path('pdf_download/<str:c>/', views.DownloadPDF.as_view(), name="pdf-download"),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += crud_for_model(SelectCourse, views=['all_courses'],
                    add_form=SelectCourseForm, update_form=SelectCourseForm )

students_record/urls.py
from django.contrib import admin
from django.urls import include, path

from users import views
from setquestions.views import setquestions, save_choice
from quiz.views import quiz_view, save_quiz, js, save_ans
from django.contrib.auth import views as auth_views
# from users.views import CustomLoginView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('assignment/', include('assignment.urls', namespace='assignment_app')),
    # path('setquestions/', include('setquestions.urls', namespace='assignment_app')),
    path('setquestions/', setquestions, name='set-questions'),


    path('save_choice/<int:question_pk>/<str:choice_text>/', save_choice, name='save-choice'),
    path('admin/', admin.site.urls),
    path('register_student/', views.register, name='register'),
    path('profile/<int:pk>/<int:i_n>/', views.profile, name='profile'),
    path('back/<str:pk>/', views.back, name='back'),
    path('login_success/', views.login_success, name='login-success'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('user_exists/<int:i_n>/', views.user_exists, name='user-exists'),
]

# , namespace='assignment-section')
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

users/urls.py
# from django.urls import path
# from . import views
# from django.conf import settings
# from django.contrib.auth import views as auth_views
# from .views import CustomLoginView

# urlpatterns = [
#     path('', views.register, name='register'),
#     path('profile/', views.profile, name='profile'),
#     path('login/', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
#     path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

# ]


# if settings.DEBUG:
#     from django.conf.urls.static import static
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment/models.py
from django.db import models
from .utils import Utils
from django.urls import reverse
from django.db import OperationalError
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _
# from hashid_field import HashidAutoField
import uuid
import os
import random
from binascii import hexlify
# from users.models import SelectCourse

User = get_user_model()

def _createId():
    return random.randint(1, 10000000)    #hexlify(os.urandom(16))

SEMESTER = (
        ('', 'select semester'),
        ('semester one', 'SEMESTER ONE'),
        ('semester two', 'SEMESTER TWO'),
    )
class Semester(models.Model):
    sem = models.CharField("semester", max_length=100, choices=SEMESTER)


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    photo = models.ImageField(upload_to="images/")
    attachment = models.FileField(upload_to="attachments/")
    phone = models.CharField(max_length=10)



class RegisterCourse(models.Model):
    CLASS_CHOICES = (
                ('', 'Select class'),
                ('Math1', 'Math 1'),
                ('Math2', 'Math 2'),
                ('Math3', 'Math 3'),
                ('Math4', 'Math 4'),
                )

    COURSE_CHOICES = (
                ('', 'Select a course'),
                ('Integral Equations', 'Integral Equations'),
                ('Real Functions', 'Real Functions'),
                )

    course = models.CharField(choices=COURSE_CHOICES, max_length=100)
    class_or_level = models.CharField(choices=CLASS_CHOICES, max_length=100)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('assignment_app:submit-assignment', kwargs={'pk': self.user.pk})
    

    def __str__(self):
        return f'{self.user.index_number} {self.course} ({self.class_or_level})'


COLOR_CHOICES = (
                ('', 'Select back color'),
                ('green', 'green'),
                ('blue', 'blue'),
                ('red', 'red'),
                ('burlywood', 'burlywood'),
                ('darkkhaki', 'darkkhaki'),
                ('darkslateblue', 'darkslateblue'),
                ('deeppink', 'deeppink'),
                ('fuchsia', 'fuchsia'),
                ('gold', 'gold'),
                ('indigo', 'indigo'),
                )

class SelectCourse(models.Model):
    # # # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    id = models.CharField(max_length=200, primary_key=True, default=_createId)
    courses = models.CharField(_('Course name'), max_length=200)
    choose_back_color = models.CharField(_('Course background'), default='black', max_length=200)
    date_created = models.DateTimeField(auto_now_add=True)
    sem = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.courses} -----> {self.choose_back_color}'


class StudentOtherCourse(models.Model):
    # # # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    id = models.CharField(max_length=200, primary_key=True, default=_createId)
    choose_course = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    selectcourse = models.ForeignKey(SelectCourse, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.choose_course




STATUS = (
        ('graded', 'graded'),
        ('ungraded', 'ungraded'),
    )


class UploadedFile(models.Model):
    # # # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    id = models.CharField(max_length=200, primary_key=True, default=_createId)
    pdf_file = models.FileField(upload_to="activity/")
    file_name = models.CharField(max_length=200)
    date_created = models.DateTimeField(default=Utils.get_date_time)
    course = models.CharField(max_length=200)
    submission_date = models.DateField(default=Utils.get_date_time)
    attach_info = models.TextField(blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    selectcourse = models.ForeignKey(SelectCourse, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.user}'


class ChooseActivity(models.Model):
    activity = models.CharField(max_length=200)
    index = models.CharField(max_length=200)
    course = models.CharField(max_length=200)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.activity


class Assignment(models.Model):
    # # # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    id = models.CharField(max_length=200, primary_key=True, default=_createId)
    pdf_file = models.FileField(upload_to="activity/")
    index = models.CharField(max_length=200)
    status = models.CharField(max_length=200)
    header = models.CharField(max_length=50, choices=STATUS)
    q_number = models.IntegerField()
    activity = models.CharField(max_length=200)
    file_name = models.CharField(max_length=200)
    date_submitted = models.DateTimeField(default=Utils.get_date_time)
    date_created = models.DateTimeField(default=Utils.get_date_time)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    studentothercourse = models.ForeignKey(StudentOtherCourse, on_delete=models.CASCADE)
    # uploadedfile = models.ForeignKey(UploadedFile, on_delete=models.CASCADE)
    course = models.CharField(max_length=200)
    chooseactivity = models.ForeignKey(ChooseActivity, on_delete=models.CASCADE)

    class Meta:
        # sort by "the date" in descending order unless
        # overridden in the query with order_by()
        ordering = ['-date_submitted']

    def get_absolute_url(self):
        return reverse('assignment_app:submit-assignment', kwargs={'pk': self.pk})
    

    def __str__(self):
        return f'{self.activity}'

    def encoded_id(self):
        import base64
        return base64.b64encode(str(self.user_id))

    def decode_id(self, id):
        import base64
        return base64.b64decode(id)

    @property
    def by_activity(self):
        return self.activity


TITLE = (
            ('', 'select activity'),
            ('Assignments', 'Assignments'),
            ('Exercises', 'Exercises'),
            ('Quizzes', 'Quizzes'),
            ('Trial Works', 'Trial Works')
    )

class StudentResult(models.Model):
    

    STATUS = (
            ('', 'select status'),
            ('graded', 'graded'),
            ('not graded', 'not graded'),
    )
    # # # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    id = models.CharField(max_length=200, primary_key=True, default=_createId)
    q_number = models.IntegerField()
    title = models.CharField(max_length=50, choices=TITLE)
    status = models.CharField(max_length=50, choices=STATUS)
    scored = models.FloatField("score")
    total = models.FloatField()
    course = models.CharField(max_length=200)
    marker = models.CharField(max_length=200)
    date_graded = models.DateField(default=Utils.get_date)
    date_graded1 = models.DateTimeField(default=Utils.get_date_time)    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    assignment = models.ForeignKey(Assignment, on_delete=models.CASCADE)
    studentothercourse = models.ForeignKey(StudentOtherCourse, on_delete=models.CASCADE)


    class Meta:
        # sort by "the date" in descending order unless
        # overridden in the query with order_by()
        ordering = ['title']


    def __str__(self):
        return f'{self.title}'

    @property
    def get_percentage(self):
        p = (self.scored / self.total) * 100
        return p

    def get_absolute_url(self):
        return reverse('assignment_app:grade-student', kwargs={'pk': self.studentothercourse.selectcourse.id, 'index':self.studentothercourse.user.index_number})





       
# SELECT_COURSE = [(c.courses, c.courses) for c in SelectCourse.objects.all()]  

SELECT_COURSE = [('Integral Equations', 'Integral Equations'),
                ('Real Ananlysis', 'Real Analysis'),
                ('Optimization', 'Optimization')]

assignment/templates/assignment/all_students.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
    

    <!-- ---------------------------- -->
    <div class="all-students-main-wrapper">
        
        <header>
            <nav class="navbar navbar-expand-lg navbar-light bg-info" id="navbar">
                <a class="navbar-brand text-white" id="b__fnt" href="{% url 'assignment_app:all-courses' user.pk %}">
                    <i class="fa fa-long-arrow-left" aria-hidden="true"></i>
                    {{ sel.courses|upper }}</a><span class="text-white">|</span>
                <a class="navbar-brand ml-4 text-white" id="r__fnt" href="#">{{ semester.sem|upper }}</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
            
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                    <a class="nav-link" href="#"><span class="sr-only">(current)</span></a>
                    </li>
                    
                </ul>
                <form class="form-inline my-2 my-lg-0" id="subforms">
                    <input id="q" name="q" value="{{ request.GET.q }}" class="form-control mr-sm-2" type="search" placeholder="Index number" aria-label="Search">
                    <button class="btn btn-outline-dark my-2 my-sm-0" type="submit" onclick="Bottom()">Search</button>
                </form>
                <div id="p__o">
                    <div>
                        <a href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i></a>
                    </div>
                    (shift+L)
                </div>

                <!-- <div id="l__o">
                    <li class="nav-item dropdown" id="drop">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown" id="all__elements">
                            <div class="dropdown-divider"></div>
                            <li><a class="dropdown-item" href="{% url 'logout' %}"><i class="fa fa-sign-out" aria-hidden="true"></i> Logout</a></li>
                        </ul>
                    </li>
                </div> -->
                
                </div>
            </nav>
        </header>
        
        <main>
            <div class="container" id="contner">
                <div class="m-pdf-wrapper">
                    <div class="c-pdf-wrapper">
                        <div class="c-s-pdf-wrapper">
                            {% if u_file.count == 0 %}
                                <div id="n__fl">No File(s) Uploaded</div> 
                            {% else %}
                                {% for u in u_file %}
                                    <div class="row pt-1 ml-3 mr-3">
                                        <div class="col-md-12">
                                            <div class="card bg-light" style="position: relative;">
                                                <!-- <i class="fa fa-trash-o" aria-hidden="true"></i> -->
                                                <a class="d-ass" href="#"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a>
                                                <!-- ------- -->
                                                <div class="d-dialog pl-2">
                                                    <div class="pt-1"><span style="color: orange;">date uploaded:</span> {{ u.date_created }}</div>
                                                    <div><span style="color: orange;">submission date:</span> {{ u.submission_date }}</div>
                                                    <div class="rem pb-1"><a href="{% url 'assignment_app:del-upload-file' u.pk %}"><i class="fa fa-trash-o" aria-hidden="true"></i></a></div>
                                                </div>
                                                <!-- ------------- -->
                                                <div class="card-body" id="u__wrapper">
                                                    <div id="f__name">
                                                            
                                                            <a href="{% url 'assignment_app:download-file' u.pk %}" target="_new"><i class="fa fa-file-pdf-o" aria-hidden="true"></i> <small>{{ u.file_name }}</small></a>
                                                            <!-- descriptions -->
                                                            {% if u.attach_info %}
                                                            <hr>
                                                            <div>
                                                                <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                                                                    description
                                                                </a>
                                                                <div class="collapse" id="collapseExample">
                                                                    <div class="row">
                                                                        <div class="col-md-12">
                                                                            <div class="card">
                                                                                <div class="card-body">
                                                                                    <div class="add-info">
                                                                                        {{ u.attach_info }}
                                                                                    </div>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            {% endif %}

                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <!-- --------- -->
                        </div>
                    </div>
                </div>
                
                
               <div class="set-pdf-wrapper mt-1">
                    <div class="row pt-4 ml-3 mr-3 mb-2">
                        <div class="col-md-12">
                            <div class="card bg-success">
                                <div class="card-body text-white">
                                    <form method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
                                        {{ form|crispy }}
                                        <button type="submit" class="btn btn-info">Upload</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="all-student-wrapper">
                    {% if o_c.count != 0 %}
                        <a href="{% url 'assignment_app:student-list' sel.courses sel.pk %}"><i id="rest"  class="fa fa-file-text" aria-hidden="true"></i></a>
                    {% endif %}
                    <div class="wrap-all">
                        <div class="st-particular">
                            <div class="particular-wrapper">
                                {% if o_c.count == 0 %}
                                    <div id="n__std">No Student(s) Registered For This Course</div> 
                                {% else %}
                                    {% if o_c %}
                                    {% for all_s in o_c %}
                                        <div class="pt-card">
                                            <div class="im-w">
                                                <img src="{{ all_s.user.userprofile.image.url }}" alt="">
                                            </div>
                                            <div class="indx">{{ all_s.user.index_number }}</div>
                                            <div class="t-st">
                                                {% if all_s.is_authenticated %}
                                                    <a style="color: green;" href="{% url 'assignment_app:submit-assignment' all_s.selectcourse.pk all_s.pk %}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                                {% else %}
                                                    <a href="{% url 'assignment_app:submit-assignment' all_s.selectcourse.pk all_s.pk %}"><i class="fa fa-eye" aria-hidden="true"></i></a>
                                                {% endif %}
                                            </div>
                                            {% if a.count != 0 %}
                                                <div class="t-sc">
                                                    <a style="color: green;" href="{% url 'assignment_app:grade-student' all_s.selectcourse.pk all_s.user.index_number %}"><i class="fa fa-check" aria-hidden="true"></i></a>
                                                </div>
                                            {% endif %}
                                        </div>
                                    {% endfor %}
                                    {% endif %}
                                {% endif %}
                            </div>
                        </div>
                        


                            
                    </div>
                </div>

            </div>
        </main>

        <footer class="bg-light text-center">
            <div id="fter">
                &copy; All rights reserved
            </div>
        </footer>
        
    </div>
    
    <script>
        function checkWidth(){
            // let w = document.getElementById('f__name');
            // w.trunk8()
        }

        checkWidth()

        function Bottom(){
            // document.body.scrollTop = 0;
            // document.documentElement.scrollTop = 0;
            // s_up_btn.style.display = 'none'
            
            window.scrollTo(0, document.body.scrollHeight);
        }

        // search
        
        const form = document.getElementById("subform");
        form.addEventListener("submit", getAnswers)

        function getAnswers(e){
            e.preventDefault();
            $.ajax({
                type: 'POST',
                url: "{% url 'assignment_app:all-students' 2748011 %}",
                data: $("#subform").serialize(),
                dataType: 'json',
                success: function (data){
                    if (data.msg === "Success"){
                        form.reset();
                        console.log("submitted successfully")
                    }
                }
            })
        }


    </script>

{% block javascript %}
    
{% endblock %}
{% endblock %}

assignment/templates/assignment/assignment_update_form.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
<div class="register-course">
    <div class="row">
        <div class="col-md-12">
            <div class="card bg-dark">
                <div class="card-body">
                    <form method="POST" action="." enctype="multipart/form-data" id="f__c">{% csrf_token %}
                        {{ form|crispy }}
                        <div class="form-group" id="r__c">
                            <div>
                                <button class="btn btn-outline-success" type="submit">Save</button>
                            </div>
                            <div>
                                <a class="btn btn-danger" href="{% url 'assignment_app:all-students' %}" role="button">Cancel</a>                
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

assignment/templates/assignment/grade_student.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}
<div class="grade-std-wrapper">
    <div style="font-size: 1.8em;">
        <a style="color: white;" href="{% url 'assignment_app:all-students' sel.pk %}"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
    </div>
    
    <div style="text-align: center; font-size: 1.8em; font-weight: 500; color: white; margin-bottom: 10px;">{{ sel.courses }}</div>
    <div>
        <div style="text-align: center; font-size: 1.8em; font-weight: 500; color: white; margin-bottom: 10px;">({{ request.resolver_match.kwargs.index }})</div>
    </div>
    <!-- {% regroup ass by activity as ass_list %} -->
    {% for ac in c_act %}
    <div class="row mb-4">
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="grouper mb-2">{{ ac.activity }}</div>
                    <div class="topics mb-2 bg-success pl-2 pr-2">
                        <div>File</div>
                        <div class="pl-4">Status</div>
                        <div class="mr-2">Date submitted</div>
                        <div class="pr-4">Action</div>
                    </div>
                    {% for a in ac.assignment_set.all %}
                        <div class="row mb-2">
                            <div class="col-md-12">
                                <div class="card bg-dark" id="cd__b">
                                    <div class="card-body">

                                        <div class="list-ass">

                                            <div>
                                            <div id="b__nm">{{ a.file_name }}
                                            </div>
                                            <div id="view__sol">
                                                <a class="ripple" style="color: red;" href="{% url 'assignment_app:view-assignment-pdf' a.pk %}" target="_blank"><i class="fa fa-file-pdf-o" aria-hidden="true"></i></a>
                                            </div>
                                            </div>
                                            <div>{{ a.status }}</div>
                                            <div>{{ a.date_submitted }}</div>
                                            <div>
                                                {% if a.status == 'graded' %}
                                                    {% for s in a.studentresult_set.all %}
                                                        <a class="btn btn-success" href="{% url 'assignment_app:update-grade' s.pk a.status s.studentothercourse.selectcourse.pk s.user.index_number %}" role="button">Update</a>
                                                    {% endfor %}
                                                {% else %}
                                                    <a class="btn btn-primary" href="{% url 'assignment_app:score-student-section' a.studentothercourse.pk a.pk %}" role="button">Evaluate</a>
                                                {% endif %}
                                            </div>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}

</div>
<script src="{% static 'assignment/js/hover.js' %}"></script>
<!-- <div class="swollen">
                    <div><i class="fa fa-calendar" aria-hidden="true"></i> Date Uploaded: {{ u.date_created }}</div>
                    <div><i class="fa fa-calendar" aria-hidden="true"></i> Submission Date: {{ u.submission_date }}</div>
                    </div>
                    <hr> -->
{% endblock %}

assignment/templates/assignment/selectcourse_update_form.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load filters %}
{% load crispy_forms_tags %}
{% block head %}{% endblock %}


{% block content %}

<div class="update-c">
<div class="row ml-3 mr-3 pt-4">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body h-20">
                <div id="form__wrapper">
                    <!-- create course -->
                    <form method='POST' action="." class="pt-2 blck">{% csrf_token %}
                        <div>{{ c_form|crispy }}</div>
                        <div>
                            <a class="btn btn-danger" href="{% url 'assignment_app:all-courses' s.pk %}" role="button">Cancel</a>
                            <button type="submit" class="btn btn-success">Update</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}