assignment/urls.py
from django.urls import path
# from .views import UserListView
from . import views
from cruds_adminlte.urls import crud_for_model
from .forms import SelectCourseForm
from .models import SelectCourse
from django.conf import settings
from .views import GradeUpdateView, StatusUpdateView, CourseUpdateView


app_name = 'assignment_app'
urlpatterns = [
    
    path('register_course/<str:pk>/', views.register_course, name='register-course'),
    path('main_dashboard/<str:pk>/', views.main_dashboard, name='main-dashboard'),
    path('assignment/<int:pk>/<str:i_n>/', views.submit_assignment, name='submit-assignment'),
    path('assignment/delete/<str:pk>/<str:i_n>/', views.del_assignment, name='delete-assignment'),
    path('assignment/update/<str:pk>/', views.update_assignment, name='update-assignment'),
    path('assignment/view_assignment_pdf/<str:pk>/', views.viewAssignmentPDF, name='view-assignment-pdf'),
    path('download_assignment/<str:pk>/', views.download_pdf, name='download-file'),
    path('score_student_section/<str:pk>/<str:a_pk>/', views.student_result, name='score-student-section'),
    path('assignment/all_students/<str:pk>/', views.all_students, name='all-students'),
    path('assignment/dashboard/', views.dashboard, name='dashboard'),
    path('assignment/submission_denied/<str:pk>/<str:i_n>/', views.submission_denied, name='submission-denied'),
    path('assignment/score_student_section/update/<int:pk>/<str:s>/<int:o_pk>/<int:ind>/', GradeUpdateView.as_view(), name='update-grade'),
    
    path('course/update/<str:pk>/', views.update_courses, name='update-courses'),
    
    path('update/<str:pk>/', views.update_submitted, name='update-status'),
    path('view_result/<str:pk>/<str:i_n>/', views.query_results, name='view-result'),
    path('all_courses/<str:pk>/', views.all_courses, name='all-courses'),
    path('del_courses/<str:pk>/', views.del_course, name='del-course'),
    path('del_upload_file/<str:pk>/', views.del_upload_file, name='del-upload-file'),
    path('student_dashboard/', views.student_dashboard, name='student-dashboard'),
    path('del_choose_course/<str:pk>/', views.del_choose_course, name='del-choose-course'),
    path('create_pdf/', views.create_pdf, name='create-pdf'),
    path('reults_denied/<str:pk>/', views.results_denied, name='results-denied'),
    path('student_results_list/<str:c>/<int:pk>/', views.student_results_list, name='student-list'),
    path('grade_student/<int:pk>/<int:index>/', views.grade_student, name='grade-student'),

    path('pdf_view/<str:c>/', views.ViewPDF.as_view(), name="pdf-view"),
    path('pdf_download/<str:c>/', views.DownloadPDF.as_view(), name="pdf-download"),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += crud_for_model(SelectCourse, views=['all_courses'],
                    add_form=SelectCourseForm, update_form=SelectCourseForm )

students_record/urls.py
from django.contrib import admin
from django.urls import include, path

from users import views
from setquestions.views import setquestions, save_choice
from quiz.views import quiz_view, save_quiz, js, save_ans
from django.contrib.auth import views as auth_views
# from users.views import CustomLoginView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
    path('', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('assignment/', include('assignment.urls', namespace='assignment_app')),
    # path('setquestions/', include('setquestions.urls', namespace='assignment_app')),
    path('setquestions/', setquestions, name='set-questions'),


    path('save_choice/<int:question_pk>/<str:choice_text>/', save_choice, name='save-choice'),
    path('admin/', admin.site.urls),
    path('register_student/', views.register, name='register'),
    path('profile/<int:pk>/<int:i_n>/', views.profile, name='profile'),
    path('back/<str:pk>/', views.back, name='back'),
    path('login_success/', views.login_success, name='login-success'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('user_exists/<int:i_n>/', views.user_exists, name='user-exists'),
]

# , namespace='assignment-section')
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

 

users/urls.py
# from django.urls import path
# from . import views
# from django.conf import settings
# from django.contrib.auth import views as auth_views
# from .views import CustomLoginView

# urlpatterns = [
#     path('', views.register, name='register'),
#     path('profile/', views.profile, name='profile'),
#     path('login/', CustomLoginView.as_view(template_name='users/login.html'), name='login'),
#     path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

# ]


# if settings.DEBUG:
#     from django.conf.urls.static import static
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth import get_user_model
from hashid_field import HashidAutoField
import uuid
# from assignment.models import StudentOtherCourse



User = get_user_model()


COURSE_CHOICES = (
                ('', 'Select a course'),
                ('Integral Equations', 'Integral Equations'),
                ('Real Analysis', 'Real Analysis'),
)





# SELECT_COURSE = [(c.courses, c.courses) for c in SelectCourse.objects.all()]  



class UserProfile(models.Model):
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='users/profile_pics/default1.png', upload_to='users/profile_pics')

    def __str__(self):
        return f'{self.user.index_number} profile'

users/forms.py
from django import forms
from .models import UserProfile, COURSE_CHOICES
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.core.exceptions import ValidationError
# from assignment.models import SELECT_COURSE
User = get_user_model()

STATUS = (
            ('graded', 'graded'),
             ('not graded', 'graded'),
    )
class UserRegisterForm(UserCreationForm):
    
    # course = forms.ChoiceField(choices=SELECT_COURSE)
    email = forms.EmailField(max_length=150)
    index_number = forms.CharField(max_length=150)

    class Meta:
        model = User
        fields = ('index_number', 'email', 'password1', 'password2',)
      

    def clean_index_number(self, *args, **kwargs):
        index = self.cleaned_data.get('index_number')
        qs = User.objects.filter(index_number=index)
        if qs.exists():
            raise forms.ValidationError("This index number has already been used!")
        return index


    def save(self, commit=True):
        user = super(UserRegisterForm, self).save(commit=False)
        user.index_number = self.cleaned_data['index_number']

        if commit:
            user.save()
            print('Its saved')
        return user
    

class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField(max_length=150)
    index_number = forms.CharField(max_length=150)
    # course = forms.CharField(widget=forms.Select(choices=COURSE_CHOICES), max_length=100)

    def clean_index_number(self, *args, **kwargs):
        ind = self.cleaned_data.get('index_number')
        u = User.objects.filter(index_number=ind).exists()
        if u:
            raise ValidationError('User with this index number already exists')
        return ind


    class Meta:
        model = User
        fields = ('index_number', 'email',)
        
    

class UserProfileUpdateForm(forms.ModelForm): 
    class Meta:
        model = UserProfile
        fields = ['image']



# class CustomAuthenticationForm(AuthenticationForm):
#     index_number = UsernameField(
#         label='Index number',
#         widget=forms.TextInput(attrs={'autofocus': True})
#     )

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.contrib.auth.views import LoginView
from .forms import (UserRegisterForm, 
                UserProfileUpdateForm, UserUpdateForm)
from assignment.models import StudentOtherCourse, Assignment, SelectCourse, ChooseActivity
User = get_user_model()

def register(request):
    if request.method == 'POST':
        u_form = UserRegisterForm(request.POST)
        if u_form.is_valid():
            u_form.save()
            index_number = u_form.cleaned_data.get('index_number')
            index_num = u_form.cleaned_data.get('index')
            messages.success(request, "Registered successfully!!!")
            return HttpResponseRedirect(reverse('login'))
    else:
        u_form = UserRegisterForm()
    context = {
        'u_form': u_form, 
    }
    return render(request, 'users/register.html', context)



@login_required
def profile(request, pk, i_n):
    sel = SelectCourse.objects.get(pk=pk)
    o_t = StudentOtherCourse.objects.get(id=i_n)
    ass = Assignment.objects.filter(user=o_t.user)
    ca = ChooseActivity.objects.filter(user=o_t.user)
    
    
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST or None, instance=o_t.user)
        p_form = UserProfileUpdateForm(request.POST or None, request.FILES or None, instance=o_t.user.userprofile)
        if u_form.is_valid() and p_form.is_valid():
            u = u_form.save(commit=False)
            # us = User.objects.filter(index_number=u.index_number)
            # if us.exists():
            #    return HttpResponseRedirect(reverse('user-exists', args=(i_n,)))
            # u.index_number = u.index_number
            u.save()
            if ass.exists():
                for ind in ass:
                    ind.index = u.index_number
                    ind.save() 
            if ca.exists():
                for ind in ca:
                    ind.index = u.index_number
                    ind.save() 
            
            p_form.save()
            messages.success(request, "Profile changed successfully!!!")
            return HttpResponseRedirect(reverse('profile', args=(pk,i_n,)))
        
    else:
        u_form = UserUpdateForm(instance=o_t.user)
        p_form = UserProfileUpdateForm(instance=o_t.user.userprofile)
    
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Important!
            messages.success(request, 'Your password was successfully updated!')
            return HttpResponseRedirect(reverse('profile', args=(pk,i_n,)))
        else:
            # messages.error(request, 'Please correct the error below.')
            print('...')
    else:
        form = PasswordChangeForm(request.user)

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'form': form,
        'o_t': o_t,    
        'sel': sel,
    }
    return render(request, 'users/profile.html', context)


def back(request, pk):
    u = User.objects.get(pk=pk)
    return HttpResponseRedirect(reverse('submit-assignment', args=(u.pk,)))

# class CustomLoginView(LoginView):
#     authentication_form = CustomAuthenticationForm


def login_success(request):
    if request.user.is_staff or request.user.is_superuser:
        messages.success(request, "Login successful!!!")
        return HttpResponseRedirect(reverse('assignment-section:all-courses'))
    else:
        messages.success(request, "Login successful!!!")
        return HttpResponseRedirect(reverse('assignment-section:submit-assignment'))


def user_exists(request, i_n):
    o_t = StudentOtherCourse.objects.get(id=i_n)
    context = {
        'o_t': o_t,
    }
    return render(request, 'users/user_exists.html', context)

users/templates/users/login.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="ripples" id="login__wrapper">
        <div id="login__wrapper2">
            <div class="row bg-dark text-dark" id="t__c">
                <div class="col-md-12 p-4">
                    <div class="card" id="login__box">
                        <div class="card-body w-100">
                            <form method="POST" action=".">{% csrf_token %}
                                <legend class="border-bottom mb-4">Login</legend>
                                {{ form|crispy }}
                            <div class="form-group">
                                <button class="btn btn-outline-info btn-block" type="submit">Sign In</button>
                            </div>
                            </form>

                            <div class="border-top pt-3">
                                <small class="text-muted">Need an account?<a href="{% url 'register' %}" class="ml-2">Sign Up</a></small>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>
        

{% endblock %}

users/templates/users/logout.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <!-- <div class="row text-dark">
        <div class="col-md-8">
            <div class="card">
                <div class="card-body">
                    <div class="logout"> 
                        <h3>You have logged out.<a href="{% url 'login' %}" class="ml-2">Log in</a>again?</h3>
                    </div>
                </div>
            </div>
        </div>
    </div> -->

    <div class="logout-wrapper">
        <h4>You have logged out.<a href="{% url 'login' %}"> Log in </a>again?</h4>
    </div>
    

{% endblock %}

users/templates/users/profile.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    
    <div class="row" id="user__profile">
        <div class="col-md-12">
            <div class="card">
                <a href="{% url 'assignment_app:submit-assignment' sel.pk o_t.pk %}"><i class="fa fa-long-arrow-left" aria-hidden="true"></i></a>
                <div id="t__b">
                    <h5>Profile</h5>
                </div>
                <div class="card-body" id="img__wrapper">
                    <!-- <h1>{{ cur_user }}</h1> -->
                    <div id="i__w">
                        <img src="{{ o_t.user.userprofile.image.url }}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>      
    <!-- ----------- -->
    <div id="person__record">   
        <button class="btn btn-primary btn-block" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Timeline
        </button>
        
        <div class="collapse" id="collapseExample">
        <div class="card card-body" id="p__rec">
            <div class="last-l">Last joined</div>
            <div class="date-j">Date joined</div>
            <div class="act-l">{{ o_t.user.last_login }}</div>
            <div class="act-d">{{ o_t.user.date_joined }}</div>
        </div>
        </div>
    </div>
    <!-- change password -->
    <div id="person__record">   
        <button class="btn btn-success btn-block" type="button" data-toggle="collapse" data-target="#collapseExample1" aria-expanded="false" aria-controls="collapseExample">
            Change Password
        </button>
        
        <div class="collapse" id="collapseExample1">
        <div class="card card-body" id="p__recs">
            <form action="." method="POST" id="change__pass">{% csrf_token %}
                
                {{ form|crispy }}

                <div class="btn-cover">
                    <div class="btn-pass">
                        <button class="btn btn-outline-info" type="submit">Save</button>
                    </div>
                </div>
            </form>
        </div>
        </div>
    </div>
    <!-- ------------ -->
    <div class="main-wrapper"> 
        <div class="row" id="form__wrap">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action="." enctype="multipart/form-data">{% csrf_token %}
                            {{ u_form|crispy }}
                            {{ p_form|crispy }}
                            <hr style="height: 2px;">
                            <div class="form-group" id="btn__wrap">
                                <div>
                                    <button class="btn btn-outline-info" type="submit">Update</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>      
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="main-wrapper"> 
        <div class="row m-4" id="m__wrapper">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <form method="POST" action=".">{% csrf_token %}
                            <legend class="border-bottom mb-4">Register</legend>
                            {{ u_form|crispy }}
                        <div class="form-group">
                            <button class="btn btn-outline-info" type="submit">Sign Up</button>
                        </div>
                        </form>
                        <div class="border-top pt-3">
                            <small class="text-muted">Already have an account?<a href="{% url 'login' %}" class="ml-2">Sign In</a></small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        function refresh(){
            location.reload(true);
        }
        // refresh()
    </script>
{% endblock %}

users/templates/users/user_exists.html
{% extends 'assignment/base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="exists-wrapper">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body text-center">
                        <h5 class="text-dark">This index number, {{ o_t.user.index_number }} already exists</h5>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}